#Enbed Tomcat Server Port
server:
  port: 8080

#Setting ViewResolver
spring: 
  mvc: 
    view: 
      prefix: /WEB-INF/pages
      suffix: .jsp

#Custom Setting
name: mary
age: 18

profiles: 
  username: louis
  address: taiwan
  phone: "0987654321"